name: Issue Notice

on:
  issues:
    types: [opened]

jobs:
  post-notice:
    runs-on: ubuntu-latest

    steps:
      - uses: derekprior/add-autoresponse@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          respondableId: ${{ github.event.issue.node_id }}
          response: "Cider-UWP & Cider-Fujisan have been abandoned in favor of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues)."
          author: ${{ github.event.issue.user.login }}